// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_config");
},
async setConfig(args: SetConfigArgs) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_config", { args });
},
async resetConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("reset_config");
},
async getOverlayConfig() : Promise<OverlayConfig> {
    return await TAURI_INVOKE("get_overlay_config");
},
async getRealtimeStats() : Promise<Snapshot | null> {
    return await TAURI_INVOKE("get_realtime_stats");
},
async queryTrafficHistory(query: HistoryQuery) : Promise<DailyTraffic[]> {
    return await TAURI_INVOKE("query_traffic_history", { query });
},
async exportTrafficCsv(args: ExportArgs) : Promise<ExportResult> {
    return await TAURI_INVOKE("export_traffic_csv", { args });
},
async getAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("get_app_info");
},
async openPath(args: OpenPathArgs) : Promise<null> {
    return await TAURI_INVOKE("open_path", { args });
},
async quitApp() : Promise<null> {
    return await TAURI_INVOKE("quit_app");
},
async showConfigWindow() : Promise<null> {
    return await TAURI_INVOKE("show_config_window");
},
async hideConfigWindow() : Promise<null> {
    return await TAURI_INVOKE("hide_config_window");
},
async resizeOverlay(args: ResizeArgs) : Promise<null> {
    return await TAURI_INVOKE("resize_overlay", { args });
},
async dockOverlayToTaskbar() : Promise<null> {
    return await TAURI_INVOKE("dock_overlay_to_taskbar");
},
async getHwSnapshot() : Promise<HwSnapshot | null> {
    return await TAURI_INVOKE("get_hw_snapshot");
},
async getHelperStatus() : Promise<HelperStatus> {
    return await TAURI_INVOKE("get_helper_status");
},
async getFanControlState() : Promise<FanControlStatus> {
    return await TAURI_INVOKE("get_fan_control_state");
},
async setFanManual(args: SetFanManualArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("set_fan_manual", { args });
},
async setFanCurve(args: SetFanCurveArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("set_fan_curve", { args });
},
async resetFanControl(args: ResetFanControlArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("reset_fan_control", { args });
},
async resetAllFanControls() : Promise<FanControlStatus> {
    return await TAURI_INVOKE("reset_all_fan_controls");
},
async isAdmin() : Promise<boolean> {
    return await TAURI_INVOKE("is_admin");
},
async autostartIsEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("autostart_is_enabled");
},
async autostartEnable() : Promise<null> {
    return await TAURI_INVOKE("autostart_enable");
},
async autostartDisable() : Promise<null> {
    return await TAURI_INVOKE("autostart_disable");
},
async scanCleanup() : Promise<ScanResult> {
    return await TAURI_INVOKE("scan_cleanup");
},
async cleanCategories(args: CleanArgs) : Promise<CleanResult> {
    return await TAURI_INVOKE("clean_categories", { args });
},
async scanLargeFiles(args: LargeFileScanArgs) : Promise<LargeFileScanResult> {
    return await TAURI_INVOKE("scan_large_files", { args });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppConfig = { schemaVersion: number; general: GeneralConfig; overlay: OverlayConfig; network: NetworkConfig; history: HistoryConfig }
export type AppInfo = { name: string; version: string; os: string; arch: string; configDir: string; logsDir: string; dbFile: string }
export type CleanArgs = { categoryIds: string[]; excludedPaths: string[] }
export type CleanResult = { freedBytes: number; deletedFiles: number; errors: string[] }
export type CleanupCategory = { id: string; name: string; description: string; sizeBytes: number; fileCount: number; paths: PathDetail[] }
export type CpuHw = { name: string; packageTempC: number | null; perCoreTempsC?: (number | null)[]; perCoreUsage?: number[]; totalUsage: number; frequencyMhz: number | null; powerW: number | null }
export type CpuSnapshot = { usagePercent: number; perCore: number[] | null; model: string; physicalCores: number }
export type DailyTraffic = { date: string; iface: string | null; bytesRecv: number; bytesSent: number }
export type DiskHw = { index: number; model: string; bus: string; tempC: number | null; health: string; readBytesPerSec: number | null; writeBytesPerSec: number | null; totalBytes: number; usedBytes: number | null; identifier: string }
export type ExportArgs = { query: HistoryQuery; path: string }
export type ExportResult = { savedTo: string; rows: number }
export type FanControlEntry = { fanId: string; mode: FanControlMode; manualPwm: number; curve: FanCurvePoint[]; lastWrittenPwm: number | null; writeFailures: number }
export type FanControlMode = "bios" | "manual" | "curve"
export type FanControlStatus = { fuseHold: boolean; fuseReason: string | null; maxTempC: number | null; entries: FanControlEntry[] }
export type FanCurvePoint = { tempC: number; pwm: number }
export type FanHw = { id: string; name: string; rpm: number | null; pwmPercent: number | null; controllable: boolean }
export type GeneralConfig = { sampleIntervalMs: number; 
/**
 * When true, the sampler dynamically adjusts the interval based on system activity.
 * Active (CPU>50% or net>1MB/s) → 500ms, idle → 2000ms.
 * The `sample_interval_ms` field is ignored when adaptive is enabled.
 */
adaptiveInterval: boolean }
export type GpuHw = { index: number; name: string; vendor: string; usagePercent: number | null; memUsedMb: number | null; memTotalMb: number | null; tempC: number | null; powerW: number | null; fanRpm: number | null; fanPwm: number | null }
export type HelperStatus = "starting" | "running" | "restarting" | "unavailable"
export type HelperStatusEvent = { status: HelperStatus; reason?: string | null }
export type HistoryConfig = { retainDays: number }
export type HistoryGranularity = "day" | "month"
export type HistoryQuery = { from: string; to: string; granularity?: HistoryGranularity; iface: string | null }
export type HwSnapshot = { timestampMs: number; cpu: CpuHw | null; gpus?: GpuHw[]; memory: MemoryHw | null; disks?: DiskHw[]; motherboard: MotherboardHw | null; fans?: FanHw[] }
export type InterfaceStats = { luid: number; name: string; description: string; isUp: boolean; isPhysical: boolean; bytesSentTotal: number; bytesRecvTotal: number; acceptedBytesSentTotal: number; acceptedBytesRecvTotal: number; bytesSentPerSec: number; bytesRecvPerSec: number }
export type IpcError = { code: string; message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LargeFile = { path: string; sizeBytes: number }
export type LargeFileScanArgs = { root: string; minSizeMb: number; limit: number }
export type LargeFileScanResult = { files: LargeFile[]; totalScanned: number }
export type MemoryHw = { totalBytes: number; usedBytes: number; usedPercent: number; swapTotalBytes: number; swapUsedBytes: number; modules?: MemoryModule[]; frequencyMhz: number | null; channels: number | null }
export type MemoryModule = { slot: string; capacityBytes: number; speedMtps: number | null; manufacturer: string; partNumber: string }
export type MemorySnapshot = { totalBytes: number; usedBytes: number; usedPercent: number; swapTotalBytes: number; swapUsedBytes: number }
export type MotherboardHw = { vendor: string; model: string; superIo: string | null; temperaturesC?: NamedValue[]; voltagesV?: NamedValue[] }
export type NamedValue = { name: string; value: number; identifier?: string }
export type NetworkConfig = { monitorMode: NetworkMonitorMode; monitorInterfaces: string[]; includeLoopback: boolean; includeVirtual: boolean }
export type NetworkMonitorMode = "all" | "specified"
export type NetworkSnapshot = { interfaces: InterfaceStats[]; total: InterfaceStats; sampleIntervalMs: number }
export type OpenPathArgs = { path: string }
export type OverlayConfig = { items: OverlayItem[] }
export type OverlayItem = "net-down" | "net-up" | "cpu" | "cpu-freq" | "mem" | "disk-read" | "disk-write" | "gpu" | "cpu-temp" | "gpu-temp" | "gpu-usage" | "disk-temp" | "fan-rpm" | "mb-temp"
export type PathDetail = { path: string; sizeBytes: number; fileCount: number }
export type ResetFanControlArgs = { fanId: string }
export type ResizeArgs = { width: number; height: number }
export type ScanResult = { categories: CleanupCategory[]; totalSizeBytes: number; totalFileCount: number }
export type SetConfigArgs = { patch: JsonValue }
export type SetFanCurveArgs = { fanId: string; curve: FanCurvePoint[] }
export type SetFanManualArgs = { fanId: string; pwm: number }
export type Snapshot = { timestampMs: number; cpu: CpuSnapshot; memory: MemorySnapshot; network: NetworkSnapshot }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
