// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async aiGetMcpOverview() : Promise<AiMcpOverview> {
    return await TAURI_INVOKE("ai_get_mcp_overview");
},
async aiGetMcpServers(args: AiMcpClientArgs) : Promise<AiMcpServerItem[]> {
    return await TAURI_INVOKE("ai_get_mcp_servers", { args });
},
async aiDiscoverMcpServers(args: AiMcpClientArgs) : Promise<string[]> {
    return await TAURI_INVOKE("ai_discover_mcp_servers", { args });
},
async aiToggleMcpServer(args: AiToggleMcpServerArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_toggle_mcp_server", { args });
},
async aiDeleteMcpServer(args: AiMcpServerArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_delete_mcp_server", { args });
},
async aiCopyMcpServer(args: AiCopyMcpServerArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_copy_mcp_server", { args });
},
async aiMcpOauthStatus(args: AiMcpServerArgs) : Promise<AiMcpOAuthStatus> {
    return await TAURI_INVOKE("ai_mcp_oauth_status", { args });
},
async aiMcpOauthAuthorize(args: AiMcpServerArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_mcp_oauth_authorize", { args });
},
async aiMcpOauthCancel(args: AiMcpServerArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_mcp_oauth_cancel", { args });
},
async aiMcpOauthRefresh(args: AiMcpServerArgs) : Promise<AiMcpOAuthStatus> {
    return await TAURI_INVOKE("ai_mcp_oauth_refresh", { args });
},
async aiMcpOauthRevoke(args: AiMcpServerArgs) : Promise<string> {
    return await TAURI_INVOKE("ai_mcp_oauth_revoke", { args });
},
async aiListSessionTree() : Promise<AiSessionTree> {
    return await TAURI_INVOKE("ai_list_session_tree");
},
async aiLoadSession(args: AiLoadSessionArgs) : Promise<AiSessionPage> {
    return await TAURI_INVOKE("ai_load_session", { args });
},
async aiDeleteSession(args: AiSessionArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_delete_session", { args });
},
async aiDeleteWorkspace(args: AiWorkspaceArgs) : Promise<null> {
    return await TAURI_INVOKE("ai_delete_workspace", { args });
},
async aiExportSession(args: AiExportSessionArgs) : Promise<string> {
    return await TAURI_INVOKE("ai_export_session", { args });
},
async aiRevealSessionFile(args: AiSessionArgs) : Promise<string> {
    return await TAURI_INVOKE("ai_reveal_session_file", { args });
},
async aiRefreshSessionCache() : Promise<null> {
    return await TAURI_INVOKE("ai_refresh_session_cache");
},
async getConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("get_config");
},
async setConfig(args: SetConfigArgs) : Promise<AppConfig> {
    return await TAURI_INVOKE("set_config", { args });
},
async resetConfig() : Promise<AppConfig> {
    return await TAURI_INVOKE("reset_config");
},
async getOverlayConfig() : Promise<OverlayConfig> {
    return await TAURI_INVOKE("get_overlay_config");
},
async getRealtimeStats() : Promise<Snapshot | null> {
    return await TAURI_INVOKE("get_realtime_stats");
},
async queryTrafficHistory(query: HistoryQuery) : Promise<DailyTraffic[]> {
    return await TAURI_INVOKE("query_traffic_history", { query });
},
async exportTrafficCsv(args: ExportArgs) : Promise<ExportResult> {
    return await TAURI_INVOKE("export_traffic_csv", { args });
},
async getAppInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("get_app_info");
},
async openPath(args: OpenPathArgs) : Promise<null> {
    return await TAURI_INVOKE("open_path", { args });
},
async quitApp() : Promise<null> {
    return await TAURI_INVOKE("quit_app");
},
async showConfigWindow() : Promise<null> {
    return await TAURI_INVOKE("show_config_window");
},
async hideConfigWindow() : Promise<null> {
    return await TAURI_INVOKE("hide_config_window");
},
async resizeOverlay(args: ResizeArgs) : Promise<null> {
    return await TAURI_INVOKE("resize_overlay", { args });
},
async dockOverlayToTaskbar() : Promise<null> {
    return await TAURI_INVOKE("dock_overlay_to_taskbar");
},
async registerOverlayTooltipRegions(args: OverlayTooltipRegionsArgs) : Promise<null> {
    return await TAURI_INVOKE("register_overlay_tooltip_regions", { args });
},
async getHwSnapshot() : Promise<HwSnapshot | null> {
    return await TAURI_INVOKE("get_hw_snapshot");
},
async getHelperStatus() : Promise<HelperStatus> {
    return await TAURI_INVOKE("get_helper_status");
},
async getFanControlState() : Promise<FanControlStatus> {
    return await TAURI_INVOKE("get_fan_control_state");
},
async setFanManual(args: SetFanManualArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("set_fan_manual", { args });
},
async setFanCurve(args: SetFanCurveArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("set_fan_curve", { args });
},
async resetFanControl(args: ResetFanControlArgs) : Promise<FanControlStatus> {
    return await TAURI_INVOKE("reset_fan_control", { args });
},
async resetAllFanControls() : Promise<FanControlStatus> {
    return await TAURI_INVOKE("reset_all_fan_controls");
},
async isAdmin() : Promise<boolean> {
    return await TAURI_INVOKE("is_admin");
},
async autostartIsEnabled() : Promise<boolean> {
    return await TAURI_INVOKE("autostart_is_enabled");
},
async autostartEnable() : Promise<null> {
    return await TAURI_INVOKE("autostart_enable");
},
async autostartDisable() : Promise<null> {
    return await TAURI_INVOKE("autostart_disable");
},
async scanCleanup(args: ScanCleanupArgs | null) : Promise<ScanResult> {
    return await TAURI_INVOKE("scan_cleanup", { args });
},
async cancelCleanupScan() : Promise<boolean> {
    return await TAURI_INVOKE("cancel_cleanup_scan");
},
async exportCleanupScan(args: ExportCleanupArgs) : Promise<ExportCleanupResult> {
    return await TAURI_INVOKE("export_cleanup_scan", { args });
},
async cleanCategories(args: CleanArgs) : Promise<CleanResult> {
    return await TAURI_INVOKE("clean_categories", { args });
},
async scanLargeFiles(args: LargeFileScanArgs) : Promise<LargeFileScanResult> {
    return await TAURI_INVOKE("scan_large_files", { args });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiContentItem = { type: string; text: string }
export type AiCopyMcpServerArgs = { fromClient: string; toClient: string; name: string; overwrite: boolean }
export type AiExportSessionArgs = { workspaceHash: string; sessionId: string; format: string; path: string }
export type AiHistoryItem = { message: AiMessage }
export type AiMcpClientArgs = { client: string }
export type AiMcpClientStats = { client: string; totalServers: number; enabledServers: number }
export type AiMcpOAuthStatus = { oauthSupported: boolean | null; authorized: boolean; expiresAt: number; expiringSoon: boolean; expired: boolean; refreshFailed: boolean; needsReauth: boolean; message: string | null }
export type AiMcpOverview = { totalServers: number; enabledServers: number; clients: AiMcpClientStats[] }
export type AiMcpServerArgs = { client: string; name: string }
export type AiMcpServerItem = { name: string; client: string; type: string; detail: string; disabled: boolean }
export type AiMessage = { role: string; content: AiContentItem[]; id: string; isHidden: boolean }
export type AiSession = { sessionId: string; title: string; sessionType: string; workspaceDirectory: string; history: AiHistoryItem[]; conversationSummary: string | null }
export type AiSessionPage = { sessionId: string; title: string; sessionType: string; workspaceDirectory: string; history: AiHistoryItem[]; conversationSummary: string | null; totalMessages: number; page: number; pageSize: number }
export type AiSessionArgs = { workspaceHash: string; sessionId: string }
export type AiLoadSessionArgs = { workspaceHash: string; sessionId: string; page: number; pageSize: number }
export type AiSessionSummary = { sessionId: string; title: string; sessionType: string; workspaceDirectory: string; workspaceHash: string; messageCount: number; fileSize: number; createdAt: number | null; modifiedAt: number | null; source: string }
export type AiSessionTree = { workspaces: string[]; sessionsByWorkspace: Partial<{ [key in string]: AiSessionSummary[] }> }
export type AiToggleMcpServerArgs = { client: string; name: string; disabled: boolean }
export type AiWorkspaceArgs = { workspaceHash: string }
export type AppConfig = { schemaVersion: number; general: GeneralConfig; overlay: OverlayConfig; network: NetworkConfig; history: HistoryConfig }
export type AppInfo = { name: string; version: string; os: string; arch: string; configDir: string; logsDir: string; dbFile: string }
export type CleanArgs = { scanId: string; categoryIds: string[]; excludedPaths: string[]; confirmCaution: boolean; confirmAdvanced: boolean }
export type CleanResult = { freedBytes: number; deletedFiles: number; errors: string[] }
export type CleanupCategory = { id: string; name: string; description: string; sizeBytes: number; fileCount: number; paths: PathDetail[]; riskLevel: CleanupRisk; defaultSelected: boolean; minAgeDays: number | null }
export type CleanupRisk = "safe" | "caution" | "advanced"
export type CpuHw = { name: string; packageTempC: number | null; perCoreTempsC?: (number | null)[]; perCoreUsage?: number[]; totalUsage: number; frequencyMhz: number | null; powerW: number | null }
export type CpuSnapshot = { usagePercent: number; perCore: number[] | null; model: string; physicalCores: number }
export type DailyTraffic = { date: string; iface: string | null; bytesRecv: number; bytesSent: number }
export type DiskHw = { index: number; model: string; bus: string; tempC: number | null; health: string; readBytesPerSec: number | null; writeBytesPerSec: number | null; totalBytes: number; usedBytes: number | null; identifier: string }
export type ExportArgs = { query: HistoryQuery; path: string }
export type ExportCleanupArgs = { scanId: string; path: string; selectedCategoryIds: string[]; excludedPaths: string[] }
export type ExportCleanupResult = { savedTo: string; records: number }
export type ExportResult = { savedTo: string; rows: number }
export type FanControlEntry = { fanId: string; mode: FanControlMode; manualPwm: number; curve: FanCurvePoint[]; lastWrittenPwm: number | null; writeFailures: number }
export type FanControlMode = "bios" | "manual" | "curve"
export type FanControlStatus = { fuseHold: boolean; fuseReason: string | null; maxTempC: number | null; entries: FanControlEntry[] }
export type FanCurvePoint = { tempC: number; pwm: number }
export type FanHw = { id: string; name: string; rpm: number | null; pwmPercent: number | null; controllable: boolean }
export type GeneralConfig = { sampleIntervalMs: number; 
/**
 * When true, the sampler dynamically adjusts the interval based on system activity.
 * Active (CPU>50% or net>1MB/s) → 500ms, idle → 2000ms.
 * The `sample_interval_ms` field is ignored when adaptive is enabled.
 */
adaptiveInterval: boolean }
export type GpuHw = { index: number; name: string; vendor: string; usagePercent: number | null; memUsedMb: number | null; memTotalMb: number | null; tempC: number | null; powerW: number | null; fanRpm: number | null; fanPwm: number | null }
export type HelperStatus = "starting" | "running" | "restarting" | "unavailable"
export type HelperStatusEvent = { status: HelperStatus; reason?: string | null }
export type HistoryConfig = { retainDays: number }
export type HistoryGranularity = "day" | "month"
export type HistoryQuery = { from: string; to: string; granularity?: HistoryGranularity; iface: string | null }
export type HwSnapshot = { timestampMs: number; cpu: CpuHw | null; gpus?: GpuHw[]; memory: MemoryHw | null; disks?: DiskHw[]; motherboard: MotherboardHw | null; fans?: FanHw[] }
export type InterfaceStats = { luid: number; name: string; description: string; isUp: boolean; isPhysical: boolean; bytesSentTotal: number; bytesRecvTotal: number; acceptedBytesSentTotal: number; acceptedBytesRecvTotal: number; bytesSentPerSec: number; bytesRecvPerSec: number }
export type IpcError = { code: string; message: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LargeFile = { path: string; sizeBytes: number }
export type LargeFileScanArgs = { root: string; minSizeMb: number; limit: number }
export type LargeFileScanResult = { files: LargeFile[]; totalScanned: number }
export type MemoryHw = { totalBytes: number; usedBytes: number; usedPercent: number; swapTotalBytes: number; swapUsedBytes: number; modules?: MemoryModule[]; frequencyMhz: number | null; channels: number | null }
export type MemoryModule = { slot: string; capacityBytes: number; speedMtps: number | null; manufacturer: string; partNumber: string }
export type MemorySnapshot = { totalBytes: number; usedBytes: number; usedPercent: number; swapTotalBytes: number; swapUsedBytes: number }
export type MotherboardHw = { vendor: string; model: string; superIo: string | null; temperaturesC?: NamedValue[]; voltagesV?: NamedValue[] }
export type NamedValue = { name: string; value: number; identifier?: string }
export type NetworkConfig = { monitorMode: NetworkMonitorMode; monitorInterfaces: string[]; includeLoopback: boolean; includeVirtual: boolean }
export type NetworkMonitorMode = "all" | "specified"
export type NetworkSnapshot = { interfaces: InterfaceStats[]; total: InterfaceStats; sampleIntervalMs: number }
export type OpenPathArgs = { path: string }
export type OverlayConfig = { items: OverlayItem[] }
export type OverlayItem = "net-down" | "net-up" | "cpu" | "cpu-freq" | "mem" | "disk-read" | "disk-write" | "gpu" | "cpu-temp" | "gpu-temp" | "gpu-usage" | "disk-temp" | "fan-rpm" | "mb-temp"
export type OverlayTooltipRegion = { key: string; left: number; top: number; right: number; bottom: number }
export type OverlayTooltipRegionsArgs = { regions: OverlayTooltipRegion[] }
export type PathDetail = { path: string; sizeBytes: number; fileCount: number; matchedRule: string; source: string; volumeSerial: number | null; fileId: number | null }
export type ResetFanControlArgs = { fanId: string }
export type ResizeArgs = { width: number; height: number }
export type ScanCleanupArgs = { projectRoots: string[] }
export type ScanResult = { scanId: string; categories: CleanupCategory[]; totalSizeBytes: number; totalFileCount: number; scannedAtMs: number; expiresAtMs: number; durationMs: number; scannedPaths: number; skippedPaths: number; ignoredPaths: number; hotspotCount: number; scoutWorkers: number; engineerWorkers: number; scoutTasks: number; engineerTasks: number; projectRoots: string[]; warnings: string[]; complete: boolean; cancelled: boolean }
export type SetConfigArgs = { patch: JsonValue }
export type SetFanCurveArgs = { fanId: string; curve: FanCurvePoint[] }
export type SetFanManualArgs = { fanId: string; pwm: number }
export type Snapshot = { timestampMs: number; cpu: CpuSnapshot; memory: MemorySnapshot; network: NetworkSnapshot }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
